### ISSUE TITLE
Add support for IAM Instance profiles

### ISSUE THREAD

**Issue by brettcave** [iriusrisk/GoCD-EC2-Elastic-Agent-Plugin#10]
Deployment of EC2 instances as Go Agents currently does not support IAM Instance Profiles. Any tasks a Go Agent runs that uses an instance profile for authentication to the AWS API will not work.

Provide a way to specify an instance profile in an elastic agent profile so that ec2 instances are provisioned with an instance profile associated to them.

**Comment by v-sky** [comment]
Hello @brettcave! This feature seems very handy, thank you. I will review and test it and include to the next version as soon as I can.

**Comment by v-sky** [comment]
Feature reviewed and tested on GoCD server 20.4. Will be included into the next release.
