### ISSUE TITLE
remove "required" flag from authentication parameters in EC2

### ISSUE THREAD

**Issue by brettcave** [iriusrisk/GoCD-EC2-Elastic-Agent-Plugin#12]
If GoCD is running in EC2, and the GoCD instance has an instance profile, it may not need explicit key and secret. Allow these to be left blank, so the AWS SDK can fall back on iam instance profile authentication.

**Comment by v-sky** [comment]
Makes sense to me, related with your previous pull request #11

**Comment by brettcave** [comment]
I just picked up a bug on #11 this @v-sky - the AWS Access Key Id requires a value to be entered, but as long as the secret access is blank, it will still use default credentials. 

The EA config screen doesn't throw errors when leaving it blank, but when instance provisioning is attempted, the console indicates that this should not be blank.

**Comment by v-sky** [comment]
Feature reviewed and tested on GoCD server 20.4. Will be included into the next release.
